config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "carts#index"

  resources :carts do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :items, dependent: :destroy

  def total_price
    total = 0

    self.items.each do |item|
      subtotal = item.quantity * item.price
      total += subtotal
    end

    self.update(total:total)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :cart
  delegate :total_price, to: :cart
  after_save :total_price
  after_destroy :total_price

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def not_found
    raise ActionController::RoutingError, 'Not Found'
  rescue StandardError
    render_404
  end

  def render_404
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[show destroy]

  def index
    @carts = Cart.all
  end

  def show
    @items = @cart.items
  end

  def destroy
    respond_to do |format|
      if @cart.destroy
        format.html { redirect_to root_path, notice: 'Cart deleted successfully' }
      else
        format.html { redirect_to root_path, alert: 'Cart deletion failed' }
      end
    end
  end

  private

  def set_cart
    @cart = Cart.find(params[:id]) rescue not_found
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_cart_and_item

  def update
    respond_to do |format|
      if @item.update(item_params)
        flash[:notice] = 'Item updated successfully'
        format.json { render json: { status: 200 } }
      else
        flash[:alert] = 'Item updation failed'
        format.json { render json: { status: 501 } }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @item.destroy
        format.html { redirect_to cart_path(@cart), notice: 'Item deleted from cart successfully' }
      else
        format.html { redirect_to cart_path(@cart), alert: 'Item deletion failed' }
      end
    end
  end

  private

  def set_cart_and_item
    @cart = Cart.find(params[:cart_id])
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/carts/index.html.erb
<div class="container">
  <h1 class="text-center">My Carts</h1>

  <% @carts.each do |cart| %>
  <ul class="list-group">
    <li class="list-group-item"><%= link_to cart.number, cart_path(cart) %></li>
  </ul>
  <% end %>
</div>

app/views/carts/show.html.erb
<div class="container">
    <h1 class="text-center"><%= @cart.title %></h1>
    <h3 class="text-center">Items</h3>
    <%= render 'items/items' %>
    <div>
        <h3>Total:</h3>
        <h3 id="total"><%= @cart.total %></h3>
    </div>
    <hr />
    <%= button_to 'Delete cart', @cart, method: :delete, form: { data: {turbo_confirm: "Are you sure?"}}, class:"btn btn-outline-danger" %>
</div>

app/views/items/_items.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Item</th>
      <th scope="col">Image</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Subtotal</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.title %></td>
      <td><img src="<%= item.img %>" width="200" height="200" /></td>
      <td>
        <div class="container">
          <span id="item-quantity-<%= item.id %>"><%= item.quantity %></span>
          <div
            class="btn-group float-end"
            role="group"
          >
            <%= link_to '<i class="bi bi-plus"></i>'.html_safe,
              nil,
              remote: true, 
              class: "btn btn-outline-dark",
              id: "add-button-#{item.id}",
              data: {
                controller: "items",
                action: "items#toggleQuantity",
                items_quantity_param: "item-quantity-#{item.id}",
                items_add_param: "add-button-#{item.id}",
                items_price_param: "price-#{item.id}",
                items_subtotal_param: "subtotal-#{item.id}",
              }
            %>
            <%= link_to '<i class="bi bi-dash"></i>'.html_safe,
            nil,
            remote: true, 
            class: "btn btn-outline-dark",
            id: "minus-button-#{item.id}",
            data: {
              controller: "items",
              action: "items#toggleQuantity",
              items_quantity_param: "item-quantity-#{item.id}",
              items_minus_param: "minus-button-#{item.id}",
              items_price_param: "price-#{item.id}",
              items_subtotal_param: "subtotal-#{item.id}"
            }
          %>
          </div>
        </div>
      </td>
      <td><h5 id="price-<%= item.id %>"><%= item.price %></h5></td>
      <td>
        <div class="container">
          <h3 id="subtotal-<%= item.id %>"><%= item.quantity*item.price %></h3>
          <%= button_to 'Remove Item', cart_item_path(@cart,item), method: :delete, form: { data: {turbo_confirm: "Are you sure?"}}, class:"btn btn-outline-danger" %>
        </div>
      </td>
      <td>
        <%= link_to 'Update',
          nil,
          remote: true,
          class: "btn btn-outline-warning",
          data: {
            controller: "items",
            action: "items#updateQuantity",
            items_cart_param: "#{@cart.id}",
            items_item_param: "#{item.id}",
            items_quantity_param: "item-quantity-#{item.id}"
          }
        %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"
    />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> <%=
    javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>